"""create_all_tables

Revision ID: 45382cd74c18
Revises: 
Create Date: 2026-03-30 17:37:01.913611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45382cd74c18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_alert_type'), 'alert_logs', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_logs_id'), 'alert_logs', ['id'], unique=False)
    op.create_table('demand_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_demand', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_forecasts_forecast_date'), 'demand_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_demand_forecasts_id'), 'demand_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_demand_forecasts_sku'), 'demand_forecasts', ['sku'], unique=False)
    op.create_table('geo_risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('affected_region', sa.String(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('seendate', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_risk_events_affected_region'), 'geo_risk_events', ['affected_region'], unique=False)
    op.create_index(op.f('ix_geo_risk_events_event_type'), 'geo_risk_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_geo_risk_events_id'), 'geo_risk_events', ['id'], unique=False)
    op.create_index(op.f('ix_geo_risk_events_source'), 'geo_risk_events', ['source'], unique=False)
    op.create_index(op.f('ix_geo_risk_events_url'), 'geo_risk_events', ['url'], unique=True)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('ROUTE', 'SUPPLIER', 'CHOKEPOINT', 'REGION', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_entity_id'), 'risk_scores', ['entity_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_entity_type'), 'risk_scores', ['entity_type'], unique=False)
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_node', sa.String(), nullable=False),
    sa.Column('destination_node', sa.String(), nullable=False),
    sa.Column('transport_mode', sa.Enum('SEA', 'AIR', 'ROAD', 'RAIL', name='transportmode'), nullable=False),
    sa.Column('average_time_hours', sa.Float(), nullable=True),
    sa.Column('chokepoint_associated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_destination_node'), 'routes', ['destination_node'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_origin_node'), 'routes', ['origin_node'], unique=False)
    op.create_table('supplier_health_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('hunter_data', sa.JSON(), nullable=True),
    sa.Column('news_data', sa.JSON(), nullable=True),
    sa.Column('rapidapi_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_health_signals_id'), 'supplier_health_signals', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_health_signals_supplier_id'), 'supplier_health_signals', ['supplier_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='suppliertier'), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_domain'), 'suppliers', ['domain'], unique=True)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('po_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'APPROVED_PENDING_ERP', 'SENT', 'REJECTED', name='postatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_drafts_id'), 'po_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_po_drafts_sku'), 'po_drafts', ['sku'], unique=False)
    op.create_index(op.f('ix_po_drafts_supplier_id'), 'po_drafts', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_po_drafts_supplier_id'), table_name='po_drafts')
    op.drop_index(op.f('ix_po_drafts_sku'), table_name='po_drafts')
    op.drop_index(op.f('ix_po_drafts_id'), table_name='po_drafts')
    op.drop_table('po_drafts')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_domain'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_supplier_health_signals_supplier_id'), table_name='supplier_health_signals')
    op.drop_index(op.f('ix_supplier_health_signals_id'), table_name='supplier_health_signals')
    op.drop_table('supplier_health_signals')
    op.drop_index(op.f('ix_routes_origin_node'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_node'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_entity_type'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_entity_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_geo_risk_events_url'), table_name='geo_risk_events')
    op.drop_index(op.f('ix_geo_risk_events_source'), table_name='geo_risk_events')
    op.drop_index(op.f('ix_geo_risk_events_id'), table_name='geo_risk_events')
    op.drop_index(op.f('ix_geo_risk_events_event_type'), table_name='geo_risk_events')
    op.drop_index(op.f('ix_geo_risk_events_affected_region'), table_name='geo_risk_events')
    op.drop_table('geo_risk_events')
    op.drop_index(op.f('ix_demand_forecasts_sku'), table_name='demand_forecasts')
    op.drop_index(op.f('ix_demand_forecasts_id'), table_name='demand_forecasts')
    op.drop_index(op.f('ix_demand_forecasts_forecast_date'), table_name='demand_forecasts')
    op.drop_table('demand_forecasts')
    op.drop_index(op.f('ix_alert_logs_id'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_alert_type'), table_name='alert_logs')
    op.drop_table('alert_logs')
    # ### end Alembic commands ###
