FROM python:3.11-slim

RUN pip install --no-cache-dir mlflow

WORKDIR /app

CMD ["sh", "-c", "mlflow server \
  --host 0.0.0.0 \
  --port $PORT \
  --backend-store-uri sqlite:///mlflow.db \
  --default-artifact-root ./artifacts \
  --workers 1 \
  --allowed-hosts '*' \
  --cors-allowed-origins '*'"]